minimumReleaseAge: 0
# minimumReleaseAge: 10080

publicHoistPattern:
  # For @dnd-kit
  - '@dnd-kit/utilities'
  - '@dnd-kit/modifiers'

  # For codegen
  - '@graphql-codegen/plugin-helpers'
  - '@graphql-typed-document-node/core'
  - graphql

  # For react-scripts-vite
  - eslint
  - vite
  - vitest

  # For @mui v7 upgrade
  - '@mui/system'
