fragment GameListFields on Game {
  id
  name
  notes
  tags
  rating
  installed_at

  # Only used for a length / presence check.
  previous_file_state {
    __typename
  }

  play_sessions {
    duration
    ended_at
    passive
  }
}

fragment GameDialogFields on Game {
  id
  name

  rating
  description
  notes
  tags

  source_port
  iwad_id
  extra_mod_ids

  use_custom_config

  previous_file_state {
    ...GameDialogFileListPreviousFileStateFields
  }
}

# Used in the iwad / mods fields.
fragment GameDialogOptionFields on Game {
  id
  name
  tags
}

fragment GameDialogFileListPreviousFileStateFields on PreviousFileStateItem {
  is_enabled
  relative
}

fragment GameDialogFileListFields on GameFileEntry {
  absolute
  relative
}

query getGameListQuery {
  getGames {
    ...GameListFields
  }
}

query getGameDialogFields($game_id: ID!) {
  getGame(id: $game_id) {
    ...GameDialogFields
  }

  getGames {
    ...GameDialogOptionFields
  }
}

query getGameFiles($game_ids: [ID!]!) {
  getGameFiles(game_ids: $game_ids) {
    ...GameDialogFileListFields
  }
}

mutation openGamesFolder($game_id: ID) {
  openGamesFolder(game_id: $game_id)
}

mutation startGame($game_id: ID!) {
  startGame(game_id: $game_id)
}

mutation updateGame($game: GameInput!) {
  updateGame(game: $game) {
    ...GameDialogFields
  }
}

mutation updateNotes($game_id: ID!, $notes: String!) {
  updateNotes(game_id: $game_id, notes: $notes) {
    id
    notes
  }
}

mutation setRating($game_id: ID!, $rating: Int!) {
  updateRating(game_id: $game_id, rating: $rating) {
    id
    rating
  }
}

mutation setTags($game_id: ID!, $tags: [String!]!) {
  updateTags(game_id: $game_id, tags: $tags) {
    id
    tags
  }
}

mutation downloadGame($host: String!, $hint: String) {
  downloadGame(host: $host, hint: $hint) {
    success
    message
    temp_path
  }
}
