fragment ModSetDialogFields on ModSet {
  name
  mods
}

fragment ModSetFormFields on Game {
  id
  name
}

query getAllModSets {
  getModSets {
    ...ModSetDialogFields
  }
}

query getModSetsFormFields {
  getGames {
    id
    ...ModSetFormFields
  }
}

mutation createModSet($mod_set: CreateModSetInput!) {
  createModSet(mod_set: $mod_set) {
    ...ModSetDialogFields
  }
}

mutation updateModSet($mod_set: UpdateModSetInput!) {
  updateModSet(mod_set: $mod_set) {
    ...ModSetDialogFields
  }
}

mutation deleteModSet($name: ID!) {
  deleteModSet(name: $name)
}
