#!/usr/bin/env bash
set -ex

./script/prepare-env

npx --yes concurrently \
  'npx --yes nodemon --watch ./schema.graphql --exec ./node_modules/.bin/graphql-codegen' \
  './node_modules/.bin/react-scripts-vite start' \
  './node_modules/.bin/tauri dev'
