fragment SourcePortsDialogFields on SourcePort {
  id
  command
  known_source_port_id
  is_default
}

fragment KnownSourcePortCardFields on KnownSourcePort {
  id
  name
  home_page_url
  download_page_url
  supports_custom_config
  supports_save_dir
  example_command
}

query getAllSourcePorts {
  getSourcePorts {
    ...SourcePortsDialogFields
  }

  getKnownSourcePorts {
    ...KnownSourcePortCardFields
  }

  getStarterSourcePort {
    ...KnownSourcePortCardFields
  }
}

mutation createSourcePort($source_port: CreateSourcePortInput!) {
  createSourcePort(source_port: $source_port) {
    ...SourcePortsDialogFields
  }
}

mutation updateSourcePort($source_port: UpdateSourcePortInput!) {
  updateSourcePort(source_port: $source_port) {
    ...SourcePortsDialogFields
  }
}

mutation deleteSourcePort($id: ID!) {
  deleteSourcePort(id: $id)
}
