type SourcePort {
  id: ID!
  command: [String!]!
  known_source_port_id: ID!
  is_default: Boolean!
}

type KnownSourcePort {
  id: ID!
  name: String!
  supports_custom_config: Boolean!
  supports_save_dir: Boolean!
  example_command: [String!]!
  home_page_url: String!
  download_page_url: String!
}

type Query {
  getSourcePorts: [SourcePort!]!

  getKnownSourcePorts: [KnownSourcePort!]!
  getStarterSourcePort: KnownSourcePort!
}

input CreateSourcePortInput {
  id: ID!
  command: [String!]!
  known_source_port_id: ID!

  """
  TODO Should this be a separate mutation? The field probably won't be in the
  ui for editing source ports, will probably be in the list itself.
  """
  is_default: Boolean
}

input UpdateSourcePortInput {
  id: ID!
  command: [String!]!
  known_source_port_id: ID!

  """
  TODO Should this be a separate mutation? The field probably won't be in the
  ui for editing source ports, will probably be in the list itself.
  """
  is_default: Boolean
}

type Mutation {
  createSourcePort(source_port: CreateSourcePortInput!): SourcePort!
  updateSourcePort(source_port: UpdateSourcePortInput!): SourcePort!
  deleteSourcePort(id: ID!): Boolean!
}
